### ISSUE TITLE
Crash with error message on ping

### ISSUE THREAD

**Issue by g-vidal** [drtyhlpr/rpi23-gen-image#83] opened 2017-06-07 13:06 UTC
I cannot build a stretch image any more the process terminates with :

```
W: Failure while installing base packages.  This will be re-attempted up to five times.
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/iputils-ping_3W: Failure while installing base packages.  This will be re-attempted up to five times.
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/iputils-ping_3W: Failure while installing base packages.  This will be re-attempted up to five times.
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/iputils-ping_3W: Failure while installing base packages.  This will be re-attempted up to five times.
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/iputils-ping_3W: Failure while installing base packages.  This will be re-attempted up to five times.
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/iputils-ping_3+ cleanup
+ set +x
killing processes using mount point ...
removing temporary mount points ...
```
I checked the log and the problem seems to come from ping

```
dpkg: regarding .../iputils-ping_3%3a20161105-1_armhf.deb containing iputils-ping:
 inetutils-ping conflicts with ping
  iputils-ping provides ping and is to be installed.

dpkg: error processing archive /var/cache/apt/archives/iputils-ping_3%3a20161105-1_armhf.deb (--unpack):
 conflicting packages - not installing iputils-ping
```
I tried to exclude ping with no effect.

Can anybody help on that issue please.
Thanks

Update
update : I cannot also  prevent installing Xorg ans all X graphics dependencies

**Comment by quozl** [comment] 2017-06-07 23:59
I'm not surprised.  Stretch is currently a moving target, and may occasionally not build.  Either;

* wait until the problem is fixed by Debian developers, or
* go back in time to a previous set of Stretch packages, using http://snapshot.debian.org/ in your sources, or
* reproduce the problem with Debian tools alone (such as debootstrap and not rpi23-gen-image) and report it to Debian, or
* diagnose and fix the problem yourself.

You might also look at a fork of rpi23-gen-image to see if it fares any differently; see https://github.com/michaelfranzl/rpi23-gen-image

**Comment by brianmay** [comment] 2017-06-19 23:03
I built stretch fine yesterday (with just some minor issues needing fixing afterward), so maybe this is fixed.

**Comment by drtyhlpr** [comment] 2017-08-21 01:08
hi, thanks for the feedback. i need some days till i have access to my rpi. no pis at my current location :( will test and fix is required.

**Comment by drtyhlpr** [comment] 2017-08-21 16:05
i tested different build configurations today and the problem should be fixed (by debian)

**Closed by drtyhlpr** 2017-08-21 16:05 UTC
